repos:
  - repo: local
    hooks:
      - id: validate-yaml
        name: Validate YAML Files
        entry: python validate_yaml.py fun.yaml conditions.yaml
        language: system
        files: ^(fun\.yaml|conditions\.yaml)$
